[[DACE]]
arch = "i686"
git-tree-sha1 = "a839157baa528e728d54dccdf0483bca47f09cc2"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "5888e65a13e76962e1433f6d757aa94d776b079c1d6e9271e532461b429fd367"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.i686-linux-musl.tar.gz"
[[DACE]]
arch = "aarch64"
git-tree-sha1 = "0da84ccc9f09090c4ed2046c48a2d411b82ed2c8"
os = "macos"

    [[DACE.download]]
    sha256 = "acdfb8bd990f8b46f48c9a03553925a97c86945eec12b76c0aecb53e8beb8b6a"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.aarch64-apple-darwin.tar.gz"
[[DACE]]
arch = "aarch64"
git-tree-sha1 = "6cf45089a242256c0410978832066ccbd01c79f3"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "da5f03f0339731bc49eaa74a7fdefc53fb4d7171222070743ae6a972be68045f"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.aarch64-linux-gnu.tar.gz"
[[DACE]]
arch = "aarch64"
git-tree-sha1 = "e2abe1853b38f3ffa3b4367e2eaa9ee6b9049e12"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "6f9060219e32369f9128aae36c5453d7bc87942395f88d0640655540977a2d8d"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.aarch64-linux-musl.tar.gz"
[[DACE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94222b78b6419b71313491ef05c37792e66f4ac6"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "8f36699169014bb63379dadec7618299bad9cdd636ef2b687266508f5a23e868"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.armv6l-linux-gnueabihf.tar.gz"
[[DACE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8197affe541ee43ed3db772bed09f82f00e93ec2"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "d5d477997ac3f14c7fb52d0a74f8b669144763d4fcd0a229264ca1c5b9900b97"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.armv6l-linux-musleabihf.tar.gz"
[[DACE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "492e078e0ebebc5ff9431f74c79994b633e46c76"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "a74a0140d5406aabae0c370636b4ff7d1f1b8169202662d89ddb7c3c7e1ceea7"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.armv7l-linux-gnueabihf.tar.gz"
[[DACE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bcf66ca274d77054cbff91b8b927cbebd02207f0"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "ab728397e708e5a45e68519e634e1dc52a5c31018996814e805593c0dffce6da"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.armv7l-linux-musleabihf.tar.gz"
[[DACE]]
arch = "i686"
git-tree-sha1 = "f9eaeb28147ba9b5f4bedf78188865b7c5943291"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "39a2cdd4ebcbb7c0c8ebc2b496f953d79c75eb92d1d7ebfcff1b083769bcc2c9"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.i686-linux-gnu.tar.gz"
[[DACE]]
arch = "powerpc64le"
git-tree-sha1 = "b9af0ce7ff47c6d1ac28f11ecbba0d229cec8a2c"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "f4187423ad64de89aaacc4d2d89ee104a01016668a46e32a37d52f1e8b17900a"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.powerpc64le-linux-gnu.tar.gz"
[[DACE]]
arch = "x86_64"
git-tree-sha1 = "15ecff2a800c5368653fd5ebd89a6d0cf9fee7a1"
os = "macos"

    [[DACE.download]]
    sha256 = "07c421641f4fa0c684f0c90b1449d64771e55c29aa23840e4f0c656b0832cb48"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.x86_64-apple-darwin.tar.gz"
[[DACE]]
arch = "x86_64"
git-tree-sha1 = "4b60422f5a0498248bccf70b538c0d6192b4dda9"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "ca26c3bd24187206db705933c2dc5b0b54496edf43b079eaae645bc2f2df2105"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.x86_64-linux-gnu.tar.gz"
[[DACE]]
arch = "x86_64"
git-tree-sha1 = "32a8ed6a3f687f51b078626844f92d4c52cb3427"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "7e3cf4184ec59a640a77162df2cb7b7280751cd27ef465137ca792862783f73d"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.3+0/DACE.v0.0.3.x86_64-linux-musl.tar.gz"
