[[DACE]]
arch = "aarch64"
git-tree-sha1 = "87e6132f3ba04628f314fed1e33c3714a1007fd0"
os = "macos"

    [[DACE.download]]
    sha256 = "11544cf8d4687587d772ff5db05b7f0025c0d4bdea2b49ec035a8dc5f879d84a"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.aarch64-apple-darwin.tar.gz"
[[DACE]]
arch = "aarch64"
git-tree-sha1 = "377383f3b85f1631040f6ec3762d7891a925f442"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "e9eaa291d380e4cbdbd7f0169a9191792bca5185a69607a47663ef96757f77b7"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.aarch64-linux-gnu.tar.gz"
[[DACE]]
arch = "aarch64"
git-tree-sha1 = "5b48b71e85bd3d438bd5a77d1b9d8ad2f7c46cf9"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "94f41b53e094bfeb25db47b86a5554ec679735a06aab2b11bd0cdca39b805689"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.aarch64-linux-musl.tar.gz"
[[DACE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8b9ad9c426e4260c6cf4fb336900d2e01a7491e"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "597c5274242d871bd5df3bce3ee5eaac2c0e99ed666b325738e46ed1e68cb5f6"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.armv6l-linux-gnueabihf.tar.gz"
[[DACE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2bd53c66488f83f5a5e8e8b8beb20e271b52fb52"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "c8e6ce8299e740ce7f099fb59e6e5237c87f7e0496592c23dfb7c9b7c0a7f712"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.armv6l-linux-musleabihf.tar.gz"
[[DACE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67f175687b674afbfa27dba14d7931feb29e7070"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "0d5c4ef85701dd3b1ed705f2e379eaebebd7b491a9b049cca97805419886dcf4"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.armv7l-linux-gnueabihf.tar.gz"
[[DACE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad1bc5698f45663a75a297d1121c333b89f62bab"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "6556d6a58f33cd46ad06f94b6ce59279f9fb8661151ba6631115b1e506619181"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.armv7l-linux-musleabihf.tar.gz"
[[DACE]]
arch = "i686"
git-tree-sha1 = "bbdf031b99d88809e42a0863f2c0fda9652e8e59"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "1f4fd37bbbd93e00f3eef4a793cb9e1ed2000d5b15f20f4adc01ec3eb628471e"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.i686-linux-gnu.tar.gz"
[[DACE]]
arch = "i686"
git-tree-sha1 = "a839157baa528e728d54dccdf0483bca47f09cc2"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "5888e65a13e76962e1433f6d757aa94d776b079c1d6e9271e532461b429fd367"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.i686-linux-musl.tar.gz"
[[DACE]]
arch = "powerpc64le"
git-tree-sha1 = "fd34790d4e9dd9c5ffe0167048d5c30341923ee2"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "9b0555285ed82bb46d4be804911b2c80fb791809c215e95731ef8d3005de3e2c"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.powerpc64le-linux-gnu.tar.gz"
[[DACE]]
arch = "x86_64"
git-tree-sha1 = "4f72207ea0b9c0b02ac40ec98a4e47e1d442d34f"
os = "macos"

    [[DACE.download]]
    sha256 = "606924ce119679078f6821fa4dbba4de9ec89b5b36aee31fcd5eafcad2e6a07d"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.x86_64-apple-darwin.tar.gz"
[[DACE]]
arch = "x86_64"
git-tree-sha1 = "5e7974fe3ea12e2179bd37746b971c9ae4ecee3d"
libc = "glibc"
os = "linux"

    [[DACE.download]]
    sha256 = "e8fba3d1b959522f22a1373b8aae4ae46cf150316fa92fc6cca7275864689dc2"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.x86_64-linux-gnu.tar.gz"
[[DACE]]
arch = "x86_64"
git-tree-sha1 = "3af05414222e360586426995148fa37330faa823"
libc = "musl"
os = "linux"

    [[DACE.download]]
    sha256 = "eda397d190eff56cd0f67c37cd9c0258f560b1ac6eeed94f7e4d99f0c0fb8c4f"
    url = "https://github.com/chrisdjscott/DACE_jll.jl/releases/download/DACE-v0.0.2+0/DACE.v0.0.2.x86_64-linux-musl.tar.gz"
